"""init_order_order_items

Revision ID: 4169468613e7
Revises:
Create Date: 2026-09-22 17:45:21.361867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4169468613e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column(
            "user_uuid",
            sa.UUID(),
            nullable=False,
            comment="Идентификатор пользователя",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED", "CONFIRMED", "CANCELLED", name="order_status_enum"
            ),
            nullable=False,
            comment="Статус заказа",
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Общая стоимость заказа",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="Валюта заказа",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_orders_user_uuid"), "orders", ["user_uuid"], unique=False
    )
    op.create_index(op.f("ix_orders_uuid"), "orders", ["uuid"], unique=False)
    op.create_table(
        "outboxs",
        sa.Column(
            "event_type", sa.String(), nullable=False, comment="Тип события"
        ),
        sa.Column(
            "sent_at", sa.DateTime(), nullable=True, comment="Время отправки"
        ),
        sa.Column(
            "entity_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный айди сущности",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_FOR_SENDING",
                "SENT",
                "CREATED",
                "UNSENT",
                "ARCHIVED",
                name="event_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_outboxs_entity_id"), "outboxs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_outboxs_event_type"), "outboxs", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outboxs_uuid"), "outboxs", ["uuid"], unique=False)
    op.create_table(
        "order_items",
        sa.Column(
            "order_uuid",
            sa.UUID(),
            nullable=False,
            comment="Идентификатор заказа",
        ),
        sa.Column(
            "product_uuid",
            sa.UUID(),
            nullable=False,
            comment="Идентификатор продукта",
        ),
        sa.Column(
            "product_name",
            sa.String(),
            nullable=False,
            comment="Название продукта на момент заказа",
        ),
        sa.Column(
            "sku",
            sa.String(),
            nullable=False,
            comment="SKU продукта на момент заказа",
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Цена одной единицы на момент заказа",
        ),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Количество"
        ),
        sa.Column(
            "total_price",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Стоимость позиции",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.ForeignKeyConstraint(
            ["order_uuid"], ["orders.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_order_items_order_uuid"),
        "order_items",
        ["order_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_product_uuid"),
        "order_items",
        ["product_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_uuid"), "order_items", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_uuid"), table_name="order_items")
    op.drop_index(
        op.f("ix_order_items_product_uuid"), table_name="order_items"
    )
    op.drop_index(op.f("ix_order_items_order_uuid"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_outboxs_uuid"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_event_type"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_entity_id"), table_name="outboxs")
    op.drop_table("outboxs")
    op.drop_index(op.f("ix_orders_uuid"), table_name="orders")
    op.drop_index(op.f("ix_orders_user_uuid"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
